### ISSUE TITLE
Text in events are being written vertically

### ISSUE THREAD

**Issue by TrevorChan1** [jwodder/schedule#2]
Hello,

I'm currently using pdfschedule as a library to create a schedule using a .py file. However, when the pdf gets generated, the text within the event boxes appears vertically. The text only has one letter per line and seems to be changing the font size to fit within the box rather than having horizontal text even though I set the font size to 12. How can I fix this? I know I'm not using the library as intended in the terminal, but is there something wrong with my code that's causing this?

Here's my code (sorry for the mess):

```
schedu = pdfschedule.Schedule(["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"])
colors = [[1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 1, 0], [0, 1, 1], [1, 0, 1], [1, 0.5, 0.5], [1, 0.5, 0], [0.5, 1, 0], [0.5, 0.5, 1], [0.5, 0, 1], [0.5, 1, 0.5], [0, 1, 0.5], [0, 0.5, 1], [1, 0.5, 1], [1, 0, 0.5], [0, 0.5, 0], [0.5, 0, 0], [0, 0, 0.5], [0.5, 0.5, 0.5]]
for i in range(1,sheet.nrows):
    out = sheet.cell_value(i,5).split()
    out2 = out[2].split('-')
    schedu.add_event(pdfschedule.Event(datetime.strptime(out[1] + out2[0], '%I:%M%p').time(),datetime.strptime(out2[1] + out[3], '%I:%M%p').time(),sheet.cell_value(i,9) + " " + sheet.cell_value(i,3) + " " + sheet.cell_value(i,0),colors[i],convertDays(out[0])))

outfile = "./User/" + name + "/" + year+ "-" + semester + " " + name + planname + ".pdf"
c = pdfschedule.Canvas(outfile,(816,1056))
c.setFont("Helvetica",16)
pwidth = 816
pheight = 1056
inch = 20
schedu.render(
        c,
        x=inch,
        y=pheight - inch,
        width=pwidth - 2 * inch,
        height=pheight/(3/2) - 2 * inch,
        font_size=16,
        show_times=True
)
c.save()
```

**Comment by jwodder** [comment]
Can you provide an [MVCE](https://stackoverflow.com/help/minimal-reproducible-example) that exhibits this problem that I can run myself?  The code you've posted relies on undefined variables like `sheet`, so I can't run it without making a whole bunch of assumptions.

**Comment by TrevorChan1** [comment]
Here's a folder with a test code with just the files needed

[pdfschedule test.zip](https://github.com/jwodder/schedule/files/8508266/pdfschedule.test.zip)

**Comment by TrevorChan1** [comment]
I was wondering if it has something to do with the text wrapping? I feel like the code gives enough room horizontally to print out the lines, and even when I just set the name of the events to "oo" it still has each letter vertical. I've been fiddling with the dimensions of the pdf and file but it doesn't seem to be changing it

**Comment by jwodder** [comment]
I believe the problem is due to the fact that `Event.text` is supposed to be a list of strings, not a single string.

**Comment by TrevorChan1** [comment]
That solved it, thank you so much!
